repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: ^(examples/|cookbook/|client_tools/|src/twinkle_client/)

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        exclude: ^(examples/|cookbook/|client_tools/|src/twinkle_client/)

  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        exclude: ^(examples/|cookbook/|client_tools/|src/twinkle_client/)

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        exclude: ^(examples/|cookbook/|client_tools/|src/twinkle_client/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(client_tools/|src/twinkle_client/)
      - id: check-yaml
        exclude: ^(client_tools/|src/twinkle_client/)
      - id: end-of-file-fixer
        exclude: ^(client_tools/|src/twinkle_client/)
      - id: requirements-txt-fixer
        exclude: ^(client_tools/|src/twinkle_client/)
      - id: double-quote-string-fixer
        exclude: ^(client_tools/|src/twinkle_client/)
      - id: check-merge-conflict
        exclude: ^(client_tools/|src/twinkle_client/)
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^(client_tools/|src/twinkle_client/)
